/** This file is generated by webpack, do not edit it. */
export type Maybe<T> = T | null;

/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Mutation = {
  __typename?: "Mutation";
  addUser: User;
};

export type MutationAddUserArgs = {
  data: NewUser;
};

export type NewUser = {
  name: Scalars["String"];
  email: Scalars["String"];
  password: Scalars["String"];
};

export type Product = {
  __typename?: "Product";
  name: Scalars["String"];
  price: Scalars["Float"];
  kind: ProductKind;
};

/** Kinds of products */
export type ProductKind = "SOUP" | "BREAD" | "MILK" | "APPLE";

export type Query = {
  __typename?: "Query";
  products: Array<Product>;
  currentUser: User;
  users: Array<User>;
};

export type User = {
  __typename?: "User";
  email: Scalars["String"];
  name: Scalars["String"];
};
