/** This file is generated by webpack, do not edit it. */
import * as Types from "../../../typings/api";

export type LoadPageDataQueryVariables = {};

export type LoadPageDataQuery = { __typename?: "Query" } & {
  currentUser: { __typename?: "User" } & Pick<Types.User, "name">;
  cart: { __typename?: "Cart" } & Pick<Types.Cart, "id" | "totalPrice">;
};

export const LoadPageData: import("graphql").DocumentNode;
