query LoadProductsData {
  products {
    id
    name
    price
    kind
    imageUrl
    specialOffer
  }
  cart {
    id
    items {
      quantity
      product {
        id
      }
    }
    totalCount
    totalPrice
  }
}
