/** This file is generated by webpack, do not edit it. */
import * as Types from "../../../typings/api";

export type LoadProductsDataQueryVariables = {};

export type LoadProductsDataQuery = { __typename?: "Query" } & {
  products: Array<
    { __typename?: "Product" } & Pick<
      Types.Product,
      "id" | "name" | "price" | "kind" | "imageUrl" | "specialOffer"
    >
  >;
  cart: { __typename?: "Cart" } & Pick<
    Types.Cart,
    "id" | "totalCount" | "totalPrice"
  > & {
      items: Array<
        { __typename?: "Item" } & Pick<Types.Item, "quantity"> & {
            product: { __typename?: "Product" } & Pick<Types.Product, "id">;
          }
      >;
    };
};

export const LoadProductsData: import("graphql").DocumentNode;
