/** This file is generated by webpack, do not edit it. */
import * as Types from "../../../client/typings/api";

export type CartUpdatedFragment = { __typename?: "Cart" } & Pick<
  Types.Cart,
  "id" | "totalCount" | "totalPrice"
> & { products: Array<{ __typename?: "Product" } & Pick<Types.Product, "id">> };

export type AddToCartMutationVariables = {
  productId: Types.Scalars["String"];
};

export type AddToCartMutation = { __typename?: "Mutation" } & {
  addToCart: { __typename?: "Cart" } & CartUpdatedFragment;
};

export type RemoveFromCartMutationVariables = {
  productId: Types.Scalars["String"];
};

export type RemoveFromCartMutation = { __typename?: "Mutation" } & {
  removeFromCart: { __typename?: "Cart" } & CartUpdatedFragment;
};

export const CartUpdated: import("graphql").DocumentNode;
export const AddToCart: import("graphql").DocumentNode;
export const RemoveFromCart: import("graphql").DocumentNode;
