mutation ChangeItemsQuantity($productId: String!, $quantity: Float!) {
  changeItemsQuantity(productId: $productId, quantity: $quantity) {
    id
    items {
      product {
        id
      }
      quantity
    }
    totalCount
    totalPrice
  }
}
