query LoadCart {
  cart {
    id
    totalCount
    totalPrice
    items {
      quantity
      product {
        id
        name
        price
        kind
        imageUrl
      }
    }
  }
}

mutation ConfirmCart($data: ConfirmCart!) {
  confirmCart(data: $data) {
    id
  }
  clearCart {
    id
    totalCount
    totalPrice
    items {
      product {
        id
      }
    }
  }
}
